---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: studybuds-frontend-v2
  namespace: argocd
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: stg/studybuds-frontend-v2
    repoURL: https://github.com/anjanliberate/studybuds-cicd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      
